//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyVysorPro {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainStringsRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainStringsRes() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyVysorPro.MainStringsRes", typeof(MainStringsRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patch for Chrome&apos;s Vysor applied successfully Start the Vysor?.
        /// </summary>
        public static string ChromeVysorInstalled {
            get {
                return ResourceManager.GetString("ChromeVysorInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You select the chrome version pather. Chrome and Vysor will closed! Continue?.
        /// </summary>
        public static string ChromeVysorInstaller {
            get {
                return ResourceManager.GetString("ChromeVysorInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Chrome extention patcher.
        /// </summary>
        public static string ChromPatcher {
            get {
                return ResourceManager.GetString("ChromPatcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download the Vysor.
        /// </summary>
        public static string DownVysor {
            get {
                return ResourceManager.GetString("DownVysor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The download has completed! Please start installing again.
        /// </summary>
        public static string DownVysorComplete {
            get {
                return ResourceManager.GetString("DownVysorComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hey.
        /// </summary>
        public static string MessageVox {
            get {
                return ResourceManager.GetString("MessageVox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You can update the program by clicking the update check button.
        /// </summary>
        public static string notifyIcMessage {
            get {
                return ResourceManager.GetString("notifyIcMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Success.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New version detected (.
        /// </summary>
        public static string Updatefinded {
            get {
                return ResourceManager.GetString("Updatefinded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Download the Vysor Package from official site? The package will load into the folder of this program.
        /// </summary>
        public static string VysorPacDown {
            get {
                return ResourceManager.GetString("VysorPacDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Are you sure you want to delete Vysor?.
        /// </summary>
        public static string VysorRemove {
            get {
                return ResourceManager.GetString("VysorRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vysor successfully deleted.
        /// </summary>
        public static string VysorRemoveSuc {
            get {
                return ResourceManager.GetString("VysorRemoveSuc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vysor 2.1.2 installed with patch.
        /// </summary>
        public static string Win212Complete {
            get {
                return ResourceManager.GetString("Win212Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have selected the full reinstaller of vysor with patch installing. Continue?.
        /// </summary>
        public static string Win212VysorQ {
            get {
                return ResourceManager.GetString("Win212VysorQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have selected the Vysor Patcher. You must have installed Vysor app of selected version. Vysor will be closed and patched! Proceed?.
        /// </summary>
        public static string Win217VysorQ {
            get {
                return ResourceManager.GetString("Win217VysorQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You have selected the windows version of patcher for Vysor. You need to select file &apos;uglify.js&apos; Continue?.
        /// </summary>
        public static string WinOtherVysorQ {
            get {
                return ResourceManager.GetString("WinOtherVysorQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Patch for Vysor applied successfully! To start Vysor press &quot;OK&quot;..
        /// </summary>
        public static string WinVysorComplete {
            get {
                return ResourceManager.GetString("WinVysorComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на You need to select &apos;uglify.js&apos;.
        /// </summary>
        public static string YouneedUglify {
            get {
                return ResourceManager.GetString("YouneedUglify", resourceCulture);
            }
        }
    }
}
